version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: innovafix_db
      MYSQL_USER: user_admin
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=innovafix_db
      - DB_USER=user_admin
      - DB_PASS=password123
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  mysql_data: