# Generated by Django 5.2.5 on 2026-03-06 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor_app', '0003_remove_usuario_rolid_alter_producto_productoid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='clienteCedula',
            new_name='cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='productoId',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='usuCedula',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='ventaCantidad',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='ventaMetodoPago',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='ventaPrecio',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='ventaTipoProducto',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rolId',
            field=models.ForeignKey(blank=True, db_column='rolId', null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor_app.rol'),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ventaId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='venta',
            table=None,
        ),
        migrations.CreateModel(
            name='ProductoVenta',
            fields=[
                ('productoventaId', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(db_column='productoId', on_delete=django.db.models.deletion.CASCADE, to='proveedor_app.producto')),
                ('venta', models.ForeignKey(db_column='ventaId', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='proveedor_app.venta')),
            ],
            options={
                'db_table': 'producto_venta',
            },
        ),
    ]
